In [1]:
#attempt to improve assignment 2
import numpy as np
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

rev_array = np.array(revenue)
exp_array = np.array(expenses)

In [2]:
profits = []
for k in range(len(revenue)):
    profits.append(rev_array[k]- exp_array[k])
prof_array = np.array(profits)
print(prof_array)

[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]


In [3]:
#pat= profit after taxes
pat = []
for k in range(len(prof_array)):
    pat.append(.7*prof_array[k])
pat_array = np.array(pat)

In [4]:
AVG_pat = np.average(pat_array)
print(AVG_pat)

1750.6813333333332


In [11]:
#creating profit margin array 
def percentage(num1, num2):
    return int(round(100*num1/num2,0))

prof_marg = []
for k in range(len(pat_array)):
    pat = percentage(pat_array[k],rev_array[k])
    prof_marg.append(pat)
prof_marg_array = np.array(prof_marg)
print(prof_marg_array)

[ 12  18 -30 -22  -5  63  50  28  23 -11   4  53]


In [10]:
good_months = []
bad_months = []
for k in range(len(prof_array)):
    good_months.append(int(round(max(0, pat_array[k]- AVG_pat),0)))
    bad_months.append(int(round(min(0,pat_array[k]-AVG_pat),0)))
good_months_array = np.array(good_months)
bad_months_array = np.array(bad_months)
print(good_months_array)
print(bad_months_array)

[  15    0    0    0    0 3335 3997 1011  579    0    0 6390]
[    0  -413 -4346 -3791 -2171     0     0     0     0 -3318 -1289     0]


In [7]:
for k in range(len(prof_array)):
    if pat_array[k] - AVG_pat > 0:
        print(k, "good month")
    elif pat_array[k] -AVG_pat < 0:
        print(k, "bad month")
    else:
        print(k, "average month")

0 good month
1 bad month
2 bad month
3 bad month
4 bad month
5 good month
6 good month
7 good month
8 good month
9 bad month
10 bad month
11 good month


In [9]:
pat_max = np.max(pat_array)
pat_min = np.min(pat_array)
print(int(round(pat_max,0)), "maximum profit after tax")
print(int(round(pat_min,0)), "minimum profit after tax")

8141 maximum profit after tax
-2595 minimum profit after tax


In [15]:
profit_after_tax_max = list([])
for i in range(len(pat_array)):
    profit_after_tax_max.append(pat_array[i] == max(pat_array))
profit_after_tax_max

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [16]:
profit_after_tax_min = list([])
for i in range(len(pat_array)):
    profit_after_tax_min.append(pat_array[i] == min(pat_array))
profit_after_tax_min

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [22]:
def number_in_thousands(value):
    return int(round(value/1000,0))
revenue_1000 = [number_in_thousands(i) for i in revenue]
expenses_1000 = [number_in_thousands(i) for i in expenses]
profit_array_1000= [number_in_thousands(i) for i in prof_array]

print(revenue_1000)
print(expenses_1000)
print(profit_array_1000)


[15, 8, 9, 9, 8, 8, 11, 10, 10, 14, 11, 15]
[12, 6, 12, 12, 9, 1, 3, 6, 7, 17, 10, 4]
[3, 2, -4, -3, -1, 7, 8, 4, 3, -2, 1, 12]
